### ISSUE TITLE
Execute permission not working

### ISSUE THREAD

**Issue by lug-gh** [OpenMediaVault-Plugin-Developers/openmediavault-resetperms#1]
Hi,

as I can see in ResetPerms.js the permissions should change to 7XX for files when using the plugin:

```
[ "700", _("Administrator: read/write, Users: no access, Others: no access") ],
                        [ "750", _("Administrator: read/write, Users: read-only, Others: no access") ],
                        [ "770", _("Administrator: read/write, Users: read/write, Others: no access") ],
                        [ "755", _("Administrator: read/write, Users: read-only, Others: read-only") ],
                        [ "775", _("Administrator: read/write, Users: read/write, Others: read-only") ],
                        [ "777", _("Everyone: read/write") ]
```
it's also written here: https://openmediavault.readthedocs.io/en/latest/administration/access_rights_management.html#id4

My problem is, when I use the plugin it changes owner/users permissions to 660 for example, instead of 770, which causes that I can't execute files directly from the smb share.

So, am I doing something wrong?

**Comment by ryecoaaron** [comment]
The plugin uses those permissions for the folders.  Because all data drives are mounted noexec on OMV, the plugin does not make the files executable. https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-resetperms/blob/master/usr/share/openmediavault/engined/rpc/resetperms.inc#L58

So, it is working as designed.

**Comment by whitevast** [comment]
It seems to me that it is necessary to make it possible to reset permissions to 777. This is necessary in many cases.

**Comment by ryecoaaron** [comment]
I can't think of a case when you would want all files to be 777.  If you are resetting permissions on a shared folder, you will likely have to change some things after.
