### ISSUE TITLE
Cannot delete the plugin from OMV6?

### ISSUE THREAD

**Issue by FAFDK** [OpenMediaVault-Plugin-Developers/openmediavault-resetperms#3]
Is there a way to uninstall it from CLI? - or a force reinstall?

After I uninstall it in Web-UI, under plugins, it still remains in the menu under services.

It also hangs when I run it, before the uninstall, on snapraid, which I do not have installed?

**Comment by FAFDK** [comment]
SOLVED!
Looks like that I had to uninstall the flash plugin, for the reset-perms to disappear from the menu?

Do they share dependencies?

I have not yet reinstalled it, because maybe it conflicts with the flash-plugin?

**Comment by ryecoaaron** [comment]
The plugin isn’t running update workbench when it is uninstalled. I will fix that when I get back from my trip. Out of curiosity, why were you removing it?

**Comment by ryecoaaron** [comment]
run:
sudo omv-mkworkbench all
to remove the plugin from the web interface.

**Comment by FAFDK** [comment]
Thank you! Well, I wanted to remove it because it did not work as expected, not on this install, maybe I did something?, but it did not work as expected, so I wanted a reinstallation, but it remained in the UI. When I uninstalled the flash plugin, the permission plugin disappeared from the UI as well, so I believe that both are supposed to update the workbench when uninstalling?

The only reason for me to uninstall it, was to make a clean fresh installation of it, to see if it would behave differently. It works as expected on my other builds, but something went wrong on this one, hence reinstallation.

**Comment by ryecoaaron** [comment]
6.0.1 in the repo now.

**Comment by FAFDK** [comment]
Just updated and installed the plugins again, but it crashes on the way out on all of them, with an `500-OK. Failed to read from socket: Connection reset by peer` notification, and it does not tell the user that the installation was successful.

When I refresh the page I see that they are installed, but the installation windows crashes with a 500 and it stops on `updating Workbench configuration files ...` ?

**Comment by ryecoaaron** [comment]
This is not a crash. It happens installing all plugins because omv-engined is restarted. Unavoidable.

**Comment by FAFDK** [comment]
Ok, thank you, my memory must serve me wrong. Cool.
